services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ragdb-postgres
    environment:
      POSTGRES_USER: mukesh
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ragdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mukesh -d ragdb"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    container_name: ragdb-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  api:
    build: .
    container_name: ragdb-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
        - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
volumes:
  postgres_data:



      
  