FROM python:3.12-slim
# Step 1 - Base image
# pyhton 3.12 on slim Debian Linux
# slim = smaller image, only essential OS packages

WORKDIR /app
#Step 2 - Set working directory inside container
#All commands below  run from this directory


RUN apt-get update && apt-get install -y \
libpq-dev \
gcc \
&& rm -rf /var/lib/apt/lists/*
#Step 3 - Install system dependencies 
#psycopg2 needs libpq-dev to compile
#gcc needed for some python packages

COPY requirements.txt .
#Step 4 - Copy requirements first
#why first? Docker caches layers
#If requirements.txt hasn't changed ->skip pip install
#Only re-install when requirements actually change
#Saves mninutes on every build

RUN pip install --no-cache-dir -r requirements.txt

#Step 5 - Install python dependencies

COPY . .
#Step 6 - Copy your application code
#Done AFTER pip install for caching benefit

EXPOSE 8000
#Step 7 - Expose the port
#Documents which port the app uses
#Does NOT actually publish the port(Docker compose handles that)

CMD ["uvicon", "main:app", "--host", "0.0.0.0", "--port","8000"]



